name: Build APK and Create GitHub Release

on:
  push:
    tags:
      - 'v*'

jobs:
  unit-tests:
    uses: zhenya-mamenko/sip-happens/.github/workflows/unit-tests.yml@main

  integration-tests:
    uses: zhenya-mamenko/sip-happens/.github/workflows/integration-tests.yml@main

  build:
    name: Install and build
    needs: [unit-tests, integration-tests]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Install Android SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-34" "build-tools;36.0.0"

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: |
          ./gradlew app:assembleRelease --no-daemon

      - name: Sign APK
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > release.keystore
          $ANDROID_SDK_ROOT/build-tools/36.0.0/apksigner sign \
            --ks release.keystore \
            --ks-key-alias ${{ secrets.KEY_ALIAS }} \
            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --key-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --out sip-happens.apk \
            app/build/outputs/apk/release/app-release-unsigned.apk
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: sip-happens.apk
          token: ${{ secrets.RELEASE_TOKEN }}
          body_path: ${{ github.workspace }}/release-notes.txt
          draft: false
          prerelease: false
          make_latest: true
